// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using turismo_oro.Infrastructure.Data;

#nullable disable

namespace turismo_oro.Infrastructure.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    partial class SqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("turismo_oro.Domain.Entities.Archivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(307)
                        .HasColumnType("character varying(307)");

                    b.Property<string>("CreatedIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(307)
                        .HasColumnType("character varying(307)");

                    b.Property<string>("DeletedIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("TamanioBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(307)
                        .HasColumnType("character varying(307)");

                    b.Property<string>("UpdatedIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Archivo", "FILE");
                });

            modelBuilder.Entity("turismo_oro.Domain.Entities.ComentarioTurismo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Calificacion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(307)
                        .HasColumnType("character varying(307)");

                    b.Property<string>("CreatedIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(307)
                        .HasColumnType("character varying(307)");

                    b.Property<string>("DeletedIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("TurismoLugarId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(307)
                        .HasColumnType("character varying(307)");

                    b.Property<string>("UpdatedIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TurismoLugarId");

                    b.ToTable("ComentarioTurismo", "TUR");
                });

            modelBuilder.Entity("turismo_oro.Domain.Entities.TurismoArchivo", b =>
                {
                    b.Property<Guid>("TurismoLugarId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArchivoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(307)
                        .HasColumnType("character varying(307)");

                    b.Property<string>("CreatedIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(307)
                        .HasColumnType("character varying(307)");

                    b.Property<string>("DeletedIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(307)
                        .HasColumnType("character varying(307)");

                    b.Property<string>("UpdatedIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TurismoLugarId", "ArchivoId");

                    b.HasIndex("ArchivoId");

                    b.ToTable("TurismoArchivo", "FILE");
                });

            modelBuilder.Entity("turismo_oro.Domain.Entities.TurismoLugar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(307)
                        .HasColumnType("character varying(307)");

                    b.Property<string>("CreatedIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(307)
                        .HasColumnType("character varying(307)");

                    b.Property<string>("DeletedIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Destacados")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EtiquetaPrecio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Latitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<decimal>("Longitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(307)
                        .HasColumnType("character varying(307)");

                    b.Property<string>("UpdatedIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("TurismoLugar", "TUR");
                });

            modelBuilder.Entity("turismo_oro.Domain.Entities.ComentarioTurismo", b =>
                {
                    b.HasOne("turismo_oro.Domain.Entities.TurismoLugar", "TurismoLugar")
                        .WithMany("Comentarios")
                        .HasForeignKey("TurismoLugarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TurismoLugar");
                });

            modelBuilder.Entity("turismo_oro.Domain.Entities.TurismoArchivo", b =>
                {
                    b.HasOne("turismo_oro.Domain.Entities.Archivo", "Archivo")
                        .WithMany("TurismoArchivos")
                        .HasForeignKey("ArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("turismo_oro.Domain.Entities.TurismoLugar", "TurismoLugar")
                        .WithMany("TurismoArchivos")
                        .HasForeignKey("TurismoLugarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archivo");

                    b.Navigation("TurismoLugar");
                });

            modelBuilder.Entity("turismo_oro.Domain.Entities.Archivo", b =>
                {
                    b.Navigation("TurismoArchivos");
                });

            modelBuilder.Entity("turismo_oro.Domain.Entities.TurismoLugar", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("TurismoArchivos");
                });
#pragma warning restore 612, 618
        }
    }
}
